dependencies:
- role: andrewrothstein.bash
  version: v1.1.3
- role: andrewrothstein.unarchive-deps
  version: v1.0.12
galaxy_info:
  author: Andrew Rothstein
  company: BlackRock
  description: installs Miniconda
  galaxy_tags:
  - python
  - conda
  - miniconda
  license:
  - MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - all
