- name: install the os dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
  - "{{ os_dependencies }}"
  when: os_dependencies is defined

- name: fresh debians need to update
  apt:
    update_cache: yes
  when:  ansible_os_family == 'Debian'

- name: install the dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
  - git
  - ruby
  - nodejs
  - curl
  - npm
  - make
  - gcc
  - "{{ g_plus_plus }}"
  - "{{ ffi_devel_package }}"
  - "{{ libz_devel_package }}"
  - "{{ apache_package_name }}"
  - "{{ sqlite_devel_package }}"
  - "{{ ruby_devel_package }}"

- name: install all the gems we need
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    user_install: no
  loop:
  - { name: 'bundler', version: '1.13.7' }
  - { name: 'rake', version: '12.3.3' }

- name: install apache openidc mod
  package:
    name: "{{ apache_oidc_mod_package }}"
    state: present
  when: oidc_uri is defined or
        oidc_discover_uri is defined or
        oidc_discover_root is defined

- include: passenger.yml
  become: false
